config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'home/index'
  post 'home/create_receive_address', action: :create_receive_address, controller: :home
  post 'home/generate', action: :generate, controller: 'home'
  post 'home/payment', action: :payment, controller: 'home'

  get 'timestamp/index', controller: :timestamp, action: :index
  post 'timestamp/register', controller: :timestamp, action: :register
  post 'timestamp/verify', controller: :timestamp, action: :verify

  get 'token/index'
  post 'token/issue'
  post 'token/send_token'

  devise_for :users
  root to: 'home#index'
end

app/models/concerns/token.rb
class Token
  include ActiveModel::Model, TokenHelper

  attr_accessor :token_type, :amount

  validates :token_type, presence: true
  validates :amount, presence: true, if: -> {@token_type.to_i != Tapyrus::Color::TokenTypes::NFT}

  # tokenを発行
  def issue(wallet)
    @amount ||= 1
    tokens = Glueby::Contract::Token.issue!(issuer: wallet, token_type: @token_type.to_i, amount: @amount.to_i)
    token_info = tokens[0]
    token_id = token_info.color_id.payload.bth
    token_type = color_type2name(token_info.token_type)

    {id: token_id, token_type: token_type}
  end

end

app/controllers/token_controller.rb
class TokenController < ApplicationController
  include GluebyHelper, TokenHelper

  before_action :authenticate_user!
  before_action :load_wallet

  def index
    @list = @wallet.balances.select {|k,_| !k.blank?;} # TPC以外を表示
    @color_ids = @list.map {|k, _| k}
  end

  # Tokenを発行する
  def issue
    puts issue_params
    token = Token.new(issue_params)

    if token.valid?
      begin
        info = token.issue(@wallet)
        flash[:success] = "Successfully Issue Token. id=#{info[:id]}, type=#{info[:token_type]}"
      rescue Glueby::Contract::Errors::InsufficientFunds => e
        flash[:error] = "手数料が不足しています。"
      rescue Exception => e
        flash[:error] = e.message
        Rails.logger.warn e
      end
    else
      flash[:error] = token.errors.full_messages
    end

    redirect_to action: :index
  end

  # tokenを送る
  def send_token
    # TODO: Implement me
    flash[:error] = "Please implement me"
    redirect_to action: :index
  end
  private

  def issue_params
    params.require(:issue).permit(:token_type, :amount)
  end

  def load_wallet
    unless current_user.wallet_id.empty?
      @wallet = Glueby::Wallet.load(current_user.wallet_id)
    end
  end
end

app/helpers/token_helper.rb
module TokenHelper

  def color_id2rgb(color_id_hash)
    color_id_hash[2, 6]
  end

  # @description color_idをtoken_type名に変換する
  # @param color_id_hash color_idのhash表現
  def color_id2token_type(color_id_hash)
    color_id = Tapyrus::Color::ColorIdentifier.parse_from_payload(color_id_hash.htb)
    color_type2name(color_id.type)
  end

  # @description tokenの種類IDを名前に変換する
  # @param color_type tokenの種類ID
  def color_type2name(color_type)
    case color_type
    when Tapyrus::Color::TokenTypes::REISSUABLE
      "reissuable"
    when Tapyrus::Color::TokenTypes::NON_REISSUABLE
      "non_reissuable"
    when Tapyrus::Color::TokenTypes::NFT
      "NFT"
    else
      "uncolored"
    end
  end

  def token_type_options
    [["reissuable", Tapyrus::Color::TokenTypes::REISSUABLE], ["non_reissuable", Tapyrus::Color::TokenTypes::NON_REISSUABLE], ["NFT", Tapyrus::Color::TokenTypes::NFT]]
  end
end

app/views/token/index.html.erb
<%= javascript_pack_tag 'token', 'data-turbolinks-track': 'reload' %>

<!-- Section: Issue Token -->
<section class="mb-4">
  <div class="card">
    <div class="card-header py-3">
      <h5 class="mb-0 text-center"><strong>Issue Token</strong></h5>
    </div>
    <div class="card-body">
      <div class="container">

        <div class="row mt-2">
          <%= form_for "issue", :url => token_issue_url, :method => :post, :html => {:class => ''} do |f| %>

            <!-- 発行するTokenの種類と数量を入力するフォームを表示 -->
            <div class="row mt-2">
              <div class="input-group mb-3">
                <span class="input-group-text" id="issue-token_type">Token Type</span>
                <%= select_tag("issue[token_type]", options_for_select(token_type_options), {class: "form-select", "aria-label": "Token Type"}) %>
              </div>
            </div>
            <div class="row mt-2">
              <div class="input-group mb-3">
                <span class="input-group-text" id="issue-amount">Amount</span>
                <%= f.text_field :amount, type: "text", class: "form-control", id: "amount_input", placeholder: "How many issue" %>
              </div>
            </div>
            <%= f.submit "発行する", class: "btn btn-default btn-outline-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Section: Issue Token -->


<!-- Section: Send Token -->
<section class="mb-4">
  <div class="card">
    <div class="card-header py-3">
      <h5 class="mb-0 text-center"><strong>Send Token</strong></h5>
    </div>
    <div class="card-body">
      <div class="container">

        <div class="row mt-2">
          <%= form_for "send_token", :url => token_send_token_url, :method => :post, :html => {:class => ''} do |f| %>

            <!-- 送金するTokenの種類と数量と送金先アドレスを入力するフォームを表示 -->
            <div class="row mt-2">
              <div class="input-group mb-3">
                <span class="input-group-text" id="send-address-label">Address</span>
                <%= f.text_field :address, type: "address", class: "form-control", id: "address", placeholder: "Address" %>
              </div>
            </div>
            <div class="row mt-2">
              <div class="input-group mb-3">
                <span class="input-group-text" id="send-color_id">Color ID</span>
                <%= select_tag("send_token[color_id]", options_for_select(@color_ids), {class: "form-select", "aria-label": "Token Type"}) %>
              </div>
            </div>
            <div class="row mt-2">
              <div class="input-group mb-3">
                <span class="input-group-text" id="send-amount">Amount</span>
                <%= f.text_field :amount, type: "text", class: "form-control", id: "send_amount_input", placeholder: "Send token amount" %>
              </div>
            </div>
            <%= f.submit "送金する", class: "btn btn-default btn-outline-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Section: Issue Token -->


<!-- Section: Token List -->
<section class="mb-4">
  <div class="card">
    <div class="card-header text-center py-3">
      <h5 class="mb-0 text-center">
        <strong>Token List</strong>
      </h5>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-hover text-nowrap">
          <thead>
          <tr>
            <th scope="col">Color id</th>
            <th scope="col">Token Type</th>
            <th scope="col">Amount</th>
          </tr>
          </thead>
          <tbody>
          <% @list.each do |color_id, amount| %>
            <tr>
              <th scope="row"><i class="fas fa-coins pr-3" style="color: #<%= color_id2rgb(color_id) %>;" aria-hidden="true"></i> <%= color_id %></th>
              <td><!-- token type --><%= color_id2token_type(color_id) %></td>
              <td><!-- amount --><%= amount.to_i %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>
<!-- Section: Token List -->