config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'home/index'
  post 'home/create_receive_address', action: :create_receive_address, controller: :home
  post 'home/generate', action: :generate, controller: 'home'
  post 'home/payment', action: :payment, controller: 'home'

  get 'timestamp/index', controller: :timestamp, action: :index
  post 'timestamp/register', controller: :timestamp, action: :register
  post 'timestamp/verify', controller: :timestamp, action: :verify

  get 'token/index'
  post 'token/issue'
  post 'token/send_token'

  devise_for :users
  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include GluebyHelper

  before_action :authenticate_user!
  before_action :load_wallet

  def index
    @utxos = []

    if @wallet
      @receive_address = current_receive_address(@wallet)
      @utxos = @wallet.internal_wallet.list_unspent(false)
    end

    @block_height = Glueby::Internal::RPC.client.getblockcount
    @sync_block = Glueby::AR::SystemInformation.synced_block_height.int_value
  end

  # 新しい受け取りアドレスを生成する
  def create_receive_address
    @wallet.internal_wallet.receive_address(RECEIVE_ADDRESS_LABEL)
    flash[:notice] = 'Create new receive address'
    redirect_to action: :index
  end

  # ブロックを生成する
  def generate
    begin
      generate_block(@wallet)
      sync_block

      flash[:success] = 'Successfully generate block'
    rescue Tapyrus::RPC::Error => e
      Rails.logger.warn e.backtrace.join("\n")
      flash[:error] = e.message
    end
    redirect_to action: :index
  end

  # TPCを送金する
  def payment
    payment = Payment.new(payment_params)
    unless payment.valid?
      flash[:error] =  payment.errors.full_messages
    end

    begin
      payment.transfer(@wallet)
      flash[:success] = "Successfully Send TPC."
    rescue Exception => e
      flash[:error] = e.message
      Rails.logger.warn e
    end

    redirect_to action: :index
  end

  private

  def payment_params
    params.require(:payment).permit(:address, :amount)
  end

  def load_wallet
    unless current_user.wallet_id.empty?
      @wallet = Glueby::Wallet.load(current_user.wallet_id)
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
  # TPCの残高を返す
  def tpcbalance
    if @wallet
      return @wallet.balances[""].to_i / 100_000_000.to_f
    else
      return "NaN"
    end
  end
end

app/views/home/_utxo.html.erb
<tr>
  <th scope="row"><span class="<%= utxo[:finalized] ? '': 'text-warning' %>"><%= utxo[:txid] %></span></th>
  <td><%= utxo[:amount] / 100_000_000.to_f%></td>
  <td><%= utxo[:vout] %></td>
  <td><%= Tapyrus::Script.parse_from_payload(utxo[:script_pubkey].htb).addresses[0] %></td>
  <td><%= utxo[:finalized] %></td>
</tr>

app/views/home/index.html.erb
<!-- Section: wallet basic info -->
<section class="mb-4">
  <div class="card">
    <div class="card-header py-3">
      <h5 class="mb-0 text-center"><strong>Basic Info</strong></h5>
    </div>
    <div class="card-body">
      <div class="container">
        <!-- 受け取りアドレスの表示 -->
        <div class="row mt-2">
          <div class="col-sm-2">address:</div>
          <div class="col-sm-6"><strong><%= @receive_address %></strong></div>
          <div class="col-sm-4">
            <%=button_to "アドレス生成", {controller: 'home', action: 'create_receive_address'}, {method: :post, class: "btn btn-outline-primary"} %>
          </div>
        </div>

        <!-- 残高の表示 -->
        <div class="row mt-2">
          <div class="col-sm-2">balance:</div>
          <div class="col-sm-4 border-bottom">
            <h4>
            <%= tpcbalance %>
            </h4>
          </div>
          <div class="col-sm-4">TPC</div>
        </div>

        <!-- wallet idの表示 -->
        <div class="row mt-2">
          <div class="col-sm-2">wallet_id:</div>
          <div class="col-sm-8"><%= current_user.wallet_id %></div>
        </div>

      </div>
    </div>
  </div>
</section>
<!-- Section: Wallet basic info -->

<!-- Section: Payment -->
<section class="mb-4">
  <div class="card">
    <div class="card-header text-center py-3">
      <h5 class="mb-0 text-center">
        <strong>Payment</strong>
      </h5>
    </div>
    <div class="card-body">
      <div class="container">

        <%= form_for "payment", :url => home_payment_path, :method => :post, :html => {:class => ""} do |f| %>
        <!-- 支払い先アドレスとTPCを入力するフォームを表示 -->
        <div class="row mt-2">
          <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon2">Address</span>
            <%= f.text_field :address, type: "address", class: "form-control", id: "address", placeholder: "Address" %>
          </div>
        </div>
        <div class="row mt-2">
          <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon2">TPC</span>
            <%= f.text_field :amount, type: "number", step: "any", class: "form-control", id: "amount", placeholder: "Sending amount" %>
          </div>
        </div>
        <%= f.submit "送金", class: "btn btn-default btn-outline-primary" %>

        <% end %>
      </div>
    </div>
  </div>
</section>
<!-- Section: Block Info -->

<!-- Section: Block Info -->
<section class="mb-4">
  <div class="card">
    <div class="card-header text-center py-3">
      <h5 class="mb-0 text-center">
        <strong>Block Info</strong>
      </h5>
    </div>
    <div class="card-body">
      <div class="container">

        <!-- Block heightの表示と生成 -->
        <div class="row mt-2">
          <div class="col-sm-4">block height:</div>
          <div class="col-sm-4"><h5><%= @block_height %> (synced: <%= @sync_block %>)</h5></div>
          <div class="col-sm-4">
            <%=button_to "ブロック生成", {controller: 'home', action: 'generate'}, {method: :post, class: "btn btn-outline-success"} %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Section: Block Info -->

<!-- Section: UTXO List -->
<section class="mb-4">
  <div class="card">
    <div class="card-header text-center py-3">
      <h5 class="mb-0 text-center">
        <strong>UTXO List</strong>
      </h5>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-hover text-nowrap">
          <thead>
          <tr>
            <th scope="col">Transaction id</th>
            <th scope="col">Amount</th>
            <th scope="col">vout</th>
            <th scope="col">Receive Address</th>
            <th scope="col">Finalized</th>
          </tr>
          </thead>
          <tbody>
          <!-- include utxo list partial -->
          <%= render partial: "utxo", collection: @utxos  %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>
<!-- Section: UTXO List -->