config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'home/index'
  post 'home/create_receive_address', action: :create_receive_address, controller: :home
  post 'home/generate', action: :generate, controller: 'home'
  post 'home/payment', action: :payment, controller: 'home'

  get 'timestamp/index', controller: :timestamp, action: :index
  post 'timestamp/register', controller: :timestamp, action: :register
  post 'timestamp/verify', controller: :timestamp, action: :verify

  get 'token/index'
  post 'token/issue'
  post 'token/send_token'

  devise_for :users
  root to: 'home#index'
end

app/models/concerns/timestamp.rb
class Timestamp
  include ActiveModel::Model

  attr_accessor :message
  validates :message, presence: true

  # 自分が発行したtimestampのtx listを取得する
  def self.list
    Glueby::Contract::AR::Timestamp.all
  end

  # timestampを記録する
  def register(wallet)
    timestamp = Glueby::Contract::Timestamp.new(wallet: wallet, content: self.message)
    # save in active record
    ar_t = Glueby::Contract::AR::Timestamp.new(wallet_id: wallet.id, content: self.message)
    tx = timestamp.save!
    ar_t.txid = tx.txid
    ar_t.save!
    ar_t.unconfirmed! # statusをunconfirmedに更新

    tx
  end
end

app/controllers/timestamp_controller.rb
class TimestampController < ApplicationController
  include GluebyHelper

  before_action :authenticate_user!
  before_action :load_wallet

  # timestampのTOPページ表示
  def index
    @list = Timestamp.list
  end

  # 任意のメッセージの存在証明をBCに記録するアクション
  def register
    timestamp = Timestamp.new(timestamp_params)

    if timestamp.valid?
      begin
        tx = timestamp.register(@wallet)
        flash[:notice] = "Create new timestamp #{tx.txid}"
      rescue Glueby::Contract::Errors::InsufficientFunds => e
        flash[:error] = "手数料が不足しています。"
      rescue Exception => e
        flash[:error] = e.message
        Rails.logger.warn e
      end
    else
      flash[:error] = timestamp.errors.full_messages
    end

    redirect_to action: :index
  end

  # 任意のメッセージの存在証明をBCに記録するアクション
  def verify
    verifier = Verifier.new(verify_params)

    if verifier.valid? && verifier.verify_all?(@wallet)
      flash[:success] = "検証が成功しました。指定されたMessageが記録されています。"
    else
      flash[:error] = verifier.errors.full_messages
    end

    redirect_to action: :index
  end


  private

  def timestamp_params
    params.require(:timestamp).permit(:message)
  end

  def verify_params
    params.require(:verify).permit(:txid, :message)
  end

  def load_wallet
    @wallet = Glueby::Wallet.load(current_user.wallet_id)
  end

end

app/helpers/timestamp_helper.rb
module TimestampHelper
end

app/views/timestamp/index.html.erb
<!-- Section: Timestamp register -->
<section class="mb-4">
  <div class="card">
    <div class="card-header py-3">
      <h5 class="mb-0 text-center"><strong>Create Timestamp</strong></h5>
    </div>
    <div class="card-body">
      <div class="container">

        <div class="row mt-2">
        <%= form_for "timestamp", :url => timestamp_register_url, :method => :post, :html => {:class => ''} do |f| %>
          <!-- 支払い先アドレスとTPCを入力するフォームを表示 -->
          <div class="row mt-2">
            <div class="input-group mb-3">
              <span class="input-group-text" id="basic-addon2">Message</span>
              <%= f.text_field :message, type: "message", class: "form-control", id: "message", placeholder: "Any Message" %>
            </div>
          </div>
          <%= f.submit "BCに記録", class: "btn btn-default btn-outline-primary" %>
          <% end %>
        </div>
          <!-- Wallet情報の表示 -->
        <div class="row mt-2">
          <div class="col-sm-8">(残高: <%= tpcbalance %> TPC)</div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Section: Timestamp register -->

<!-- Section: Verify Timestamp -->
<section class="mb-4">
  <div class="card">
    <div class="card-header py-3">
      <h5 class="mb-0 text-center"><strong>Verify Timestamp</strong></h5>
    </div>
    <div class="card-body">
      <div class="container">

        <div class="row mt-2">
          <%= form_for "verify", :url => timestamp_verify_url, :method => :post, :html => {:class => ''} do |f| %>
            <!-- 支払い先アドレスとTPCを入力するフォームを表示 -->
            <div class="row mt-2">
              <div class="input-group mb-3">
                <span class="input-group-text" id="verify-txid">txid</span>
                <%= f.text_field :txid, type: "text", class: "form-control", id: "txid_input", placeholder: "Target Transaction" %>
              </div>
            </div>
            <div class="row mt-2">
              <div class="input-group mb-3">
                <span class="input-group-text" id="verify-message">Message</span>
                <%= f.text_field :message, type: "text", class: "form-control", id: "message_input", placeholder: "Any Message" %>
              </div>
            </div>
            <%= f.submit "検証する", class: "btn btn-default btn-outline-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Section: Verify Timestamp -->

<!-- Section: Timestamp List -->
<section class="mb-4">
  <div class="card">
    <div class="card-header text-center py-3">
      <h5 class="mb-0 text-center">
        <strong>Timestamp List</strong>
      </h5>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-hover text-nowrap">
          <thead>
          <tr>
            <th scope="col">Transaction id</th>
            <th scope="col">Content Hash</th>
            <th scope="col">Wallet ID</th>
            <th scope="col">Status</th>
          </tr>
          </thead>
          <tbody>
          <% @list.each do |t| %>
          <tr>
            <th scope="row"><span class="<%= t[:status] == 'confirmed' ? '': 'text-warning' %>"><%= t[:txid] %></span></th>
            <td><%= t[:content_hash] %></td>
            <td><%= t[:wallet_id] %></td>
            <td><%= t[:status] %></td>
          </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>
<!-- Section: Timestamp List -->