config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'home/index'
  post 'home/create_receive_address', action: :create_receive_address, controller: :home
  post 'home/generate', action: :generate, controller: 'home'
  post 'home/payment', action: :payment, controller: 'home'

  get 'timestamp/index', controller: :timestamp, action: :index
  post 'timestamp/register', controller: :timestamp, action: :register
  post 'timestamp/verify', controller: :timestamp, action: :verify

  get 'token/index'
  post 'token/issue'
  post 'token/send_token'

  devise_for :users
  root to: 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <body>

  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <!-- Container wrapper -->
    <div class="container-fluid">
      <!-- Toggle button -->
      <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars"></i>
      </button>

      <!-- Collapsible wrapper -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- Navbar brand -->
        <a class="navbar-brand mt-2 mt-lg-0" href="<%= root_url %>">
          <img
            src="<%= asset_path('tapyrus-logo2.png') %>"
            height="48"
            alt=""
            loading="lazy"
            />
        </a>
        <!-- Left links -->
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="<%= home_index_url %>">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= timestamp_index_url %>">Timestamp</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= token_index_url %>">Token</a>
          </li>
        </ul>
        <!-- Left links -->
      </div>
      <!-- Collapsible wrapper -->

      <!-- Right elements -->
      <div class="d-flex align-items-center">

        <% if user_signed_in? %>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <!-- Icon -->
              <a class="nav-link" href="<%= destroy_user_session_path %>" data-method="delete"
                 data-mdb-toggle="tooltip"
                 data-mdb-placement="bottom"
                 title="sign out">
                <%= current_user.email %> <i class="fas fa-sign-out-alt"></i>
              </a>
            </li>
          </ul>
        <% end %>
      </div>
      <!-- Right elements -->
    </div>
    <!-- Container wrapper -->
  </nav>
  <!-- Navbar -->
  </head>

  <% flash.each do |key, message| %>
    <div class="alert <%= flash_class(key) %> alert-dismissible fade show" role="alert">
      <% if message.is_a?(Array) %>
        <ul>
          <% message.each do |m| %>
          <li><%= m %></li>
          <% end %>
        </ul>
      <% else %>
        <%= message %>
      <% end %>
      <button type="button" class="btn-close" data-mdb-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>

  <main style="margin-top: 58px">
      <div class="container pt-4">
        <%= yield %>
      </div>
    </main>

  <%= javascript_pack_tag 'load_mdb', 'data-turbolinks-track': 'reload' %>
  </body>
</html>